### ISSUE TITLE
Add custom icon support to tile expand

### ISSUE THREAD

**Issue by eggp** [congthanhng/Expansion-Tile-Group#35]
Hello!

Please add custom icon support to ExpansionTileCustom.(In our project, we use a unique set of icons)
(https://github.com/congthanhng/Expansion-Tile-Group/blob/main/lib/src/core/expansion_tile_custom.dart#L489)

For further customization, I recommend delegating the Icon element, since this way you can change the size, for example... ;)

Thanks

**Comment by congthanhng** [comment]
Hi @eggp, you can use `trailing` property to replace the default icon. Hope it helpful for you. Please let me know if it work for you. 
Thanks!

**Comment by congthanhng** [comment]
Hi @eggp , thanks for your suggestion, let me consider it.

**Comment by congthanhng** [comment]
HI @eggp , thanks for your suggestion.
The first thing i want to say that I'm very appreciate your idea and understand your effort to make the package better. Please keep it in your mind and go ahead.
About this case, I think it is NOT common for all. Because it only uses for some special icons that will be rotated right side. 
You know that when we add more code lines, the performance will be reduce too. 
So i think i will close this issues.

Again, Thank you very much. Hope you guy satisfied with it.

**Comment by KiddoV** [comment]
@congthanhng  I have the same question. I have a trailing icon like:
```dart
ExpansionTileOutlined(
    trailing: Padding(padding: EdgeInsets.symmetric(horizontal: 11), child: Icon(Icons.arrow_drop_down)),
)
```
How do I change to `Icons.arrow_drop_up` when the tile expaned?
